# # Definitions of tags to detect
#
# ## General remarks
#
# - All length in meters
# - Ellipsis (...) signifies that the previous element can be repeated multiple times.
#
# ## Standalone tag definitions
# ### Remarks
#
# - name is optional
#
# ### Syntax
#
# standalone_tags:
#   [
#     {id: ID, size: SIZE, name: NAME},
#     ...
#   ]
standalone_tags:
  [
          # {id: 0, size: 0.161, name: tag_0}
#          {id: 0, size: 0.039, name: tag_0},
          {id: 0, size: 0.0385, name: tag_0},
          {id: 1, size: 0.050, name: tag_1},
#          {id: 2, size: 0.050, name: tag_2},
#          {id: 2, size: 0.0166667, name: tag_2},
          {id: 2, size: 0.015, name: tag_2}, # Tag for calibrating the bubbles
          {id: 3, size: 0.083, name: tag_3},
          {id: 4, size: 0.0333, name: ft_tag},
          { id: 5, size: 0.050, name: tag_5 },
          { id: 6, size: 0.050, name: tag_6 },
          { id: 7, size: 0.050, name: tag_7 },
          { id: 8, size: 0.02778, name: tag_8 },
          { id: 9, size: 0.02778, name: tag_9 },
          { id: 10, size: 0.02778, name: tag_10 },
          { id: 11, size: 0.03333, name: tag_11 },
          { id: 12, size: 0.03333, name: tag_12 },
          { id: 13, size: 0.02888, name: tag_13 },
          { id: 14, size: 0.02944, name: tag_14 },
          { id: 15, size: 0.02888, name: tag_15 },
          { id: 16, size: 0.02888, name: tag_16 },
          { id: 17, size: 0.02888, name: tag_17 },
          { id: 18, size: 0.030, name: tag_18 },
          { id: 19, size: 0.030, name: tag_19 },
          { id: 20, size: 0.030, name: tag_20 },
          { id: 21, size: 0.030, name: tag_21 },
          { id: 22, size: 0.030, name: tag_22 },
          { id: 23, size: 0.030, name: tag_23 },
#          { id: 30, size: 0.015, name: tag_30 },
#          { id: 31, size: 0.015, name: tag_31 },
#          { id: 32, size: 0.015, name: tag_32 },

  ]
# ## Tag bundle definitions
# ### Remarks
#
# - name is optional
# - x, y, z have default values of 0 thus they are optional
# - qw has default value of 1 and qx, qy, qz have default values of 0 thus they are optional
#
# ### Syntax
#
# tag_bundles:
#   [
#     {
#       name: 'CUSTOM_BUNDLE_NAME',
#       layout:
#         [
#           {id: ID, size: SIZE, x: X_POS, y: Y_POS, z: Z_POS, qw: QUAT_W_VAL, qx: QUAT_X_VAL, qy: QUAT_Y_VAL, qz: QUAT_Z_VAL},
#           ...
#         ]
#     },
#     ...
#   ]
tag_bundles:
  [
#    {
#      name: 'bundle_1',
#      layout:
#      [
#            {id: 20, size: 0.02778, x: -0.06, y: -0.06, z: 0., qw: 1, qx: 0, qy: 0, qz: 0},
#            {id: 21, size: 0.02778, x: 0.06, y: 0.06, z: 0., qw: 1, qx: 0, qy: 0, qz: 0},
#            {id: 22, size: 0.02778, x: -0.06, y: 0.06, z: 0., qw: 1, qx: 0, qy: 0, qz: 0},
#      ]
#
#    },
    {
      name: 'tag_bundle_calibration',
      layout:
        [
          { id: 100, size: 0.03, x: 0., y: -0.054, z: 0., qx: 0, qy: 0, qz: 0, qw: 1},
          { id: 101, size: 0.03, x: 0.054, y: 0., z: 0., qx: 0, qy: 0, qz: 0.70710678, qw: 0.70710678},
          { id: 102, size: 0.03, x: 0., y: 0.054, z: 0., qx: 0, qy: 0, qz: 1, qw: 0},
          { id: 103, size: 0.03, x: -0.054, y: -0., z: 0., qx: 0, qy: 0, qz: 0.70710678, qw: -0.70710678},
        ]

    },
    #    {
#    {
#      name: 'tag_300',
#      layout:
#      [
#            {id: 30, size: 0.015, x: -0.0135, y: 0.0135, z: 0., qw: 1, qx: 0, qy: 0, qz: 0},
#            {id: 31, size: 0.015, x: 0.0145,  y: 0.0135, z: 0., qw: 1, qx: 0, qy: 0, qz: 0},
#            {id: 32, size: 0.015, x: -0.0145, y: 0.0135, z: 0., qw: 1, qx: 0, qy: 0, qz: 0},
#      ]
#    }
  ]
